### ISSUE TITLE
Ts3-Viewer not displayed correctly

### ISSUE THREAD

**Issue by Rustypredator** [Rustypredator/ts3wi_bootstrap#1]
The Tree view in "serverview" is bugged  
works fine externally though (different css being loaded)

**Comment by D4RKNOISE** [comment]
Got the same problem....

**Comment by D4RKNOISE** [comment]
in index.tpl

Replace: 
`<!--<link rel="stylesheet" href="templates/{$tmpl}/gfx/css/tsview.css" type="text/css" media="screen" />-->`

With:
`<link rel="stylesheet" type="text/css" href="templates/{$tmpl}/gfx/css/tsview.css" media="screen"/>`

**Comment by Rustypredator** [comment]
Wow, ok... i completely forgot about that css file  
That fixes the viewer. Thank you.  
Fixed: 9bd8758
