### ISSUE TITLE
No content is delivered to the client (white screen)

### ISSUE THREAD

**Issue by Axel1492** [Rustypredator/ts3wi_bootstrap#3]
ts3wi version: [Beta 3.4.3.1](http://interface.ts-rent.de/smf/index.php?page=Thread&postID=4634#post4634)
bootstrap version: [0.0.1](../releases/tag/0.0.1)
PHP version: 7.0.x
Server: IIS 7.5

Not sure how to figure out the problem. If you give me some hint I will try to narrow this down. I have full control over the server.

**Comment by Rustypredator** [comment]
Sorry, i dont have any experience reagarding IIS.  
Can you try to inspect the site, and see if you have any content at all? (Strg+U displays source code)  
Also, what browser are you using?
  
Error logs for IIS should be somewhere like ```C:\windows\temp\php70_errors.log``` Depending on PHP version.  
As there could be an PHP error. Look for errors with the WI path.

**Comment by Axel1492** [comment]
I am using Firefox Developer Edition (but same in Internet Explorer).

With no content I meant that really nothing is transmitted. So nothing there when inspecting the source code.

**Comment by Rustypredator** [comment]
Okay, anything in the PHP Log? maybe there is a typo somewhere in my code...  
When im home I'll be going to test  with the release zip if i can recreate this

**Comment by Rustypredator** [comment]
I could not recreate your White screen with a fresh installation of the Webinterface.

**Comment by Rustypredator** [comment]
@Axel1492 Please make sure, you have the right permissions set for the folders! This may solve your error... (Suggested on Forumpost)  
I dont know, what permissions are required for windows though...

**Comment by Axel1492** [comment]
You were right ...actually my PHP configuration itself was a bit messed up as well.

Important for ts3wi to run properly `read/write/change` permissions on the foler `./template_c/` for PHP are necessary. This is due to the theme being compiled prior to usage. This is not necessary when the standard theme is used as it comes precompiled as it looks like.
