### ISSUE TITLE
Missing Style on Ts channel oeverview...

### ISSUE THREAD

**Issue by D4RKNOISE** [Rustypredator/ts3wi_bootstrap#4]
Great Bootstrap...

The only thing that's not working good is the channel overview...
https://gyazo.com/a2e0644e9320557c4e861ea724e603fa

Keep up the great work!

**Comment by D4RKNOISE** [comment]
```
<link rel="stylesheet" href="templates/new/gfx/tsview.css" type="text/css" media="screen">

```
is missing.

**Comment by D4RKNOISE** [comment]
in index.tpl

Replace: 
`<!--<link rel="stylesheet" href="templates/{$tmpl}/gfx/css/tsview.css" type="text/css" media="screen" />-->`

With:
`<link rel="stylesheet" type="text/css" href="templates/{$tmpl}/gfx/css/tsview.css" media="screen"/>`

**Comment by Rustypredator** [comment]
#1 solved
